CREATE DATABASE IF NOT EXISTS TESLA_TELEMETRY;
CREATE SCHEMA IF NOT EXISTS TESLA_TELEMETRY.RAW;
CREATE SCHEMA IF NOT EXISTS TESLA_TELEMETRY.STAGING;
CREATE SCHEMA IF NOT EXISTS TESLA_TELEMETRY.CURATED;

CREATE WAREHOUSE IF NOT EXISTS TELEMETRY_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE DATABASE TESLA_TELEMETRY;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FORMAT TYPE = PARQUET USE_LOGICAL_TYPE = TRUE;
CREATE STAGE IF NOT EXISTS TELEMETRY_INTERNAL_STAGE FILE_FORMAT = PARQUET_FORMAT;
